#!/bin/bash

GLAM_ZIP=$(curl -s https://dl.feenk.com/gt/GlamorousToolkitLinux64-release)
GLAM_DIR=${GLAM_ZIP/.zip/}
GLAM_VERSION=${GLAM_DIR/*-/}

if [[ ! -d $GLAM_DIR ]]
then
    echo
    echo installing $GLAM_DIR ...
    wget -q https://dl.feenk.com/gt/$GLAM_ZIP
    mkdir $GLAM_DIR
    pushd $GLAM_DIR >& /dev/null
        unzip -q ../$GLAM_ZIP
    popd >& /dev/null
    rm $GLAM_ZIP
fi

pushd $GLAM_DIR >& /dev/null

    MISSING=$(ldd lib/libSkia.so | grep "not found")
    if [[ "$MISSING" != "" ]]
    then
        echo need updated libstdc++
        echo
        read -p "install ? " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]
        then
            exit 1
       fi
       set -x
       sudo add-apt-repository ppa:ubuntu-toolchain-r/test
       sudo apt-get install -y g++-10
       set +x
       echo
   fi
    
   echo
   echo starting $GLAM_VERSION
   ./bin/GlamorousToolkit-cli --interactive GlamorousToolkit.image st ../load.st

popd >& /dev/null

git status
